export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      birth_records: {
        Row: {
          id: string;
          registry_number: string;
          registration_date: string;
          child_name: string;
          child_sex: string;
          date_of_birth: string;
          place_of_birth: string;
          father_name: string | null;
          father_age: number | null;
          father_birthplace: string | null;
          father_citizenship: string | null;
          mother_name: string | null;
          mother_age: number | null;
          mother_birthplace: string | null;
          mother_citizenship: string | null;
          informant_name: string | null;
          informant_relationship: string | null;
          informant_address: string | null;
          attendant_name: string | null;
          attendant_designation: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          registry_number: string;
          registration_date: string;
          child_name: string;
          child_sex: string;
          date_of_birth: string;
          place_of_birth: string;
          father_name?: string | null;
          father_age?: number | null;
          father_birthplace?: string | null;
          father_citizenship?: string | null;
          mother_name?: string | null;
          mother_age?: number | null;
          mother_birthplace?: string | null;
          mother_citizenship?: string | null;
          informant_name?: string | null;
          informant_relationship?: string | null;
          informant_address?: string | null;
          attendant_name?: string | null;
          attendant_designation?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          registry_number?: string;
          registration_date?: string;
          child_name?: string;
          child_sex?: string;
          date_of_birth?: string;
          place_of_birth?: string;
          father_name?: string | null;
          father_age?: number | null;
          father_birthplace?: string | null;
          father_citizenship?: string | null;
          mother_name?: string | null;
          mother_age?: number | null;
          mother_birthplace?: string | null;
          mother_citizenship?: string | null;
          informant_name?: string | null;
          informant_relationship?: string | null;
          informant_address?: string | null;
          attendant_name?: string | null;
          attendant_designation?: string | null;
          created_at?: string;
        };
      };
      death_records: {
        Row: {
          id: string;
          registry_number: string;
          registration_date: string;
          deceased_name: string;
          deceased_sex: string;
          date_of_death: string;
          place_of_death: string;
          age_at_death: number | null;
          civil_status: string | null;
          occupation: string | null;
          residence: string | null;
          cause_of_death: string | null;
          father_name: string | null;
          mother_name: string | null;
          informant_name: string | null;
          informant_relationship: string | null;
          informant_address: string | null;
          attending_physician_name: string | null;
          attending_physician_license_no: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          registry_number: string;
          registration_date: string;
          deceased_name: string;
          deceased_sex: string;
          date_of_death: string;
          place_of_death: string;
          age_at_death?: number | null;
          civil_status?: string | null;
          occupation?: string | null;
          residence?: string | null;
          cause_of_death?: string | null;
          father_name?: string | null;
          mother_name?: string | null;
          informant_name?: string | null;
          informant_relationship?: string | null;
          informant_address?: string | null;
          attending_physician_name?: string | null;
          attending_physician_license_no?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          registry_number?: string;
          registration_date?: string;
          deceased_name?: string;
          deceased_sex?: string;
          date_of_death?: string;
          place_of_death?: string;
          age_at_death?: number | null;
          civil_status?: string | null;
          occupation?: string | null;
          residence?: string | null;
          cause_of_death?: string | null;
          father_name?: string | null;
          mother_name?: string | null;
          informant_name?: string | null;
          informant_relationship?: string | null;
          informant_address?: string | null;
          attending_physician_name?: string | null;
          attending_physician_license_no?: string | null;
          created_at?: string;
        };
      };
      marriage_records: {
        Row: {
          id: string;
          registry_number: string;
          registration_date: string;
          husband_name: string;
          husband_age: number | null;
          husband_civil_status: string | null;
          husband_occupation: string | null;
          husband_residence: string | null;
          husband_citizenship: string | null;
          husband_father_name: string | null;
          husband_mother_name: string | null;
          wife_name: string;
          wife_age: number | null;
          wife_civil_status: string | null;
          wife_occupation: string | null;
          wife_residence: string | null;
          wife_citizenship: string | null;
          wife_father_name: string | null;
          wife_mother_name: string | null;
          date_of_marriage: string;
          place_of_marriage: string;
          marriage_license_number: string | null;
          minister_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          registry_number: string;
          registration_date: string;
          husband_name: string;
          husband_age?: number | null;
          husband_civil_status?: string | null;
          husband_occupation?: string | null;
          husband_residence?: string | null;
          husband_citizenship?: string | null;
          husband_father_name?: string | null;
          husband_mother_name?: string | null;
          wife_name: string;
          wife_age?: number | null;
          wife_civil_status?: string | null;
          wife_occupation?: string | null;
          wife_residence?: string | null;
          wife_citizenship?: string | null;
          wife_father_name?: string | null;
          wife_mother_name?: string | null;
          date_of_marriage: string;
          place_of_marriage: string;
          marriage_license_number?: string | null;
          minister_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          registry_number?: string;
          registration_date?: string;
          husband_name?: string;
          husband_age?: number | null;
          husband_civil_status?: string | null;
          husband_occupation?: string | null;
          husband_residence?: string | null;
          husband_citizenship?: string | null;
          husband_father_name?: string | null;
          husband_mother_name?: string | null;
          wife_name?: string;
          wife_age?: number | null;
          wife_civil_status?: string | null;
          wife_occupation?: string | null;
          wife_residence?: string | null;
          wife_citizenship?: string | null;
          wife_father_name?: string | null;
          wife_mother_name?: string | null;
          date_of_marriage?: string;
          place_of_marriage?: string;
          marriage_license_number?: string | null;
          minister_name?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
